services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=loantracker;Username=postgres;Password=postgres123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loantracker-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=loantracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loantracker-network

volumes:
  postgres_data:

networks:
  loantracker-network:
    driver: bridge
